Repository Inno-8/board-backend-server, pull requests merged in 2022-08, with the labels that each got.

#6 docs: 깃 이그노어 파일 생성 및 프로젝트 실행 후 자동으로 생성된 파일들 추가
  .gitignore
  build/classes/java/main/com/sparta/springweb/SpringwebApplication.class
  build/classes/java/main/com/sparta/springweb/controller/ContentsController.class
  build/classes/java/main/com/sparta/springweb/controller/HomeController.class
  build/classes/java/main/com/sparta/springweb/controller/PageController.class
  build/classes/java/main/com/sparta/springweb/controller/ReplyController.class
  build/classes/java/main/com/sparta/springweb/controller/UserController.class
  build/classes/java/main/com/sparta/springweb/dto/ReplyRequestDto.class
  build/classes/java/main/com/sparta/springweb/dto/SignupRequestDto.class
  build/classes/java/main/com/sparta/springweb/model/Reply.class
  build/classes/java/main/com/sparta/springweb/model/User.class
  build/classes/java/main/com/sparta/springweb/repository/UserRepository.class
  build/classes/java/main/com/sparta/springweb/security/UserDetailsImpl.class
  build/classes/java/main/com/sparta/springweb/security/UserDetailsServiceImpl.class
  build/classes/java/main/com/sparta/springweb/security/WebSecurityConfig.class
  build/classes/java/main/com/sparta/springweb/security/kakao/KakaoOAuth2.class
  build/classes/java/main/com/sparta/springweb/security/kakao/KakaoUserInfo.class
  build/classes/java/main/com/sparta/springweb/service/ContentsService.class
  build/classes/java/main/com/sparta/springweb/service/ReplyService.class
  build/classes/java/main/com/sparta/springweb/service/UserService.class
  build/resources/main/application.properties
  build/resources/main/static/detail.html
  build/resources/main/static/login.html
  build/resources/main/static/timeline.html
  build/tmp/compileJava/source-classes-mapping.txt
Labels: documentation

#10 기본키 생성 전략 변경
  src/main/java/com/sparta/springweb/model/Contents.java
  src/main/java/com/sparta/springweb/model/Reply.java
  src/main/java/com/sparta/springweb/model/User.java
Labels: bug

#12 #8: fix: Reply->Comment로 이름 변경
  src/main/java/com/sparta/springweb/controller/CommentController.java
  src/main/java/com/sparta/springweb/dto/CommentRequestDto.java
  src/main/java/com/sparta/springweb/model/Comment.java
  src/main/java/com/sparta/springweb/repository/CommentRepository.java
  src/main/java/com/sparta/springweb/repository/ReplyRepository.java
  src/main/java/com/sparta/springweb/service/CommentService.java
  src/main/java/com/sparta/springweb/service/ContentsService.java
  src/main/java/com/sparta/springweb/service/ReplyService.java
Labels: refactoring

#13 이미지 업로드 기능 구현
  src/main/java/com/sparta/springweb/config/StorageConfig.java
  src/main/java/com/sparta/springweb/controller/ContentsController.java
  src/main/java/com/sparta/springweb/dto/ContentsResponseDto.java
  src/main/java/com/sparta/springweb/dto/PostSavedResponseDto.java
  src/main/java/com/sparta/springweb/model/Contents.java
  src/main/java/com/sparta/springweb/service/ContentsService.java
  src/main/java/com/sparta/springweb/service/StorageService.java
Labels: enhancement

#16 의존성 추가 + REST API 공통 Response Body 개발
  build.gradle
  src/main/java/com/sparta/springweb/controller/CommentController.java
  src/main/java/com/sparta/springweb/controller/ContentsController.java
  src/main/java/com/sparta/springweb/controller/UserController.java
  src/main/java/com/sparta/springweb/exception/FailedConvertingException.java
  src/main/java/com/sparta/springweb/global/common/response/ApiUtils.java
  src/main/java/com/sparta/springweb/global/common/response/CommonResponse.java
  src/main/java/com/sparta/springweb/global/error/ErrorResponse.java
  src/main/java/com/sparta/springweb/global/error/GlobalExceptionHandler.java
  src/main/java/com/sparta/springweb/global/error/exception/BusinessException.java
  src/main/java/com/sparta/springweb/global/error/exception/EntityNotFoundException.java
  src/main/java/com/sparta/springweb/global/error/exception/ErrorCode.java
  src/main/java/com/sparta/springweb/global/error/exception/InvalidValueException.java
  src/main/java/com/sparta/springweb/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/springweb/repository/UserRepository.java
  src/main/java/com/sparta/springweb/service/CommentService.java
  src/main/java/com/sparta/springweb/service/ContentsService.java
  src/main/java/com/sparta/springweb/service/StorageService.java
  src/main/java/com/sparta/springweb/service/UserService.java
Labels: enhancement

#19 unique 제약조건 삭제
  src/main/java/com/sparta/springweb/model/User.java
Labels: bug

#28 #4 feat: 매일 새벽 1시, 댓글 없는 전체 게시글의 삭제를 진행하는 스케줄러 기능 추가
  src/main/java/com/sparta/springweb/SpringwebApplication.java
  src/main/java/com/sparta/springweb/service/PostService.java
  src/main/java/com/sparta/springweb/util/Scheduler.java
Labels: enhancement

#30 게시글 수정 기능 추가
  src/main/java/com/sparta/springweb/controller/PostController.java
  src/main/java/com/sparta/springweb/dto/PostUpdateRequestDto.java
  src/main/java/com/sparta/springweb/model/Post.java
  src/main/java/com/sparta/springweb/service/PostService.java
Labels: enhancement, refactoring

#32 #9 대댓글 C,R 기능 재구현
  src/main/java/com/sparta/springweb/controller/ReplyController.java
  src/main/java/com/sparta/springweb/dto/ReplyRequestDto.java
  src/main/java/com/sparta/springweb/dto/ReplyResponseDto.java
  src/main/java/com/sparta/springweb/model/Comment.java
  src/main/java/com/sparta/springweb/model/Reply.java
  src/main/java/com/sparta/springweb/repository/ReplyRepository.java
  src/main/java/com/sparta/springweb/service/ReplyService.java
Labels: bug

#34 작동안하는 테스트코드 삭제
  src/test/java/com/sparta/springweb/service/UserServiceTest.java
Labels: bug
